name: ci-security
on: [pull_request, push, workflow_dispatch]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ci-secure .

      - name: Run Snyk Docker scan (JSON Report)
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ci-secure
          args: "--severity-threshold=medium --json"

      - name: Save Snyk JSON output
        run: |
          snyk test --docker ci-secure --severity-threshold=medium --json > snyk-report.json

      - name: Convert Snyk JSON report to HTML
        run: |
          npm install -g snyk-to-html
          snyk-to-html -i snyk-report.json -o snyk-report.html

      - name: Upload Snyk HTML report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.html

      - name: Install Trivy
        run: |
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.24.0/trivy_0.24.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.24.0_Linux-64bit.deb

      - name: Run Trivy scan on Docker image
        run: |
          trivy image --severity CRITICAL,HIGH --no-progress ci-secure
